name: HTTPretty Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.9.0
          - 3.10.14
          - 3.11.9
          - 3.12.5

    steps:
    - uses: actions/checkout@v2
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v7
      with:
        default: "${{ matrix.python }}"
        command: make setup

    - name: Unit Tests
      run: make unit

    - name: Test Bugfixes
      run: make bugfixes

    - name: PyOpenSSL tests
      run: make pyopenssl

    - name: Functional Tests
      run: make functional

    - name: Upload Test Coverage Report
      uses: Atrox/codecov-action@v0.1.3

    - name: Codecov link
      run: echo "https://app.codecov.io/gh/gabrielfalcao/httpretty/"
